services:
  - type: web
    name: file-provider-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: API_ID
        value: "YOUR_API_ID"
      - key: API_HASH
        value: "YOUR_API_HASH"
      - key: BOT_TOKEN
        value: "YOUR_BOT_TOKEN"
      - key: MONGO_URI
        value: "YOUR_MONGO_URI"
